# Generated by Django 3.1.4 on 2020-12-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
