# Generated by Django 3.1.4 on 2020-12-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medicos', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('servicio', models.CharField(max_length=50)),
                ('entrada', models.IntegerField(help_text='Formato de 24 horas', null=True)),
                ('salida', models.IntegerField(help_text='Formato de 24 horas', null=True)),
                ('dias_de_trabajo', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
