# Generated by Django 3.1.4 on 2020-12-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0003_medicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicos',
            name='apellido_m',
            field=models.CharField(default='NA', help_text='Apellido materno', max_length=50),
        ),
        migrations.AddField(
            model_name='medicos',
            name='apellido_p',
            field=models.CharField(default='NA', help_text='Apellido paterno', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='dias_de_trabajo',
            field=models.CharField(help_text='Todos los dias que se va trabajar', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='nombre',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='servicio',
            field=models.CharField(help_text='Especialidad', max_length=50),
        ),
    ]
