# Generated by Django 3.1.4 on 2020-12-28 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Medicos', '0004_auto_20201228_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicos',
            name='medico',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
