# Generated by Django 3.1.4 on 2020-12-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0005_medicos_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='apellido_p',
            field=models.CharField(blank=True, help_text='Apellido paterno', max_length=50),
        ),
    ]
