# Generated by Django 3.1.4 on 2020-12-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0006_auto_20201228_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='apellido_p',
            field=models.CharField(help_text='Apellido paterno', max_length=50, null=True),
        ),
    ]
