# Generated by Django 3.1.4 on 2020-12-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0008_auto_20201228_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
