# Generated by Django 3.1.4 on 2020-12-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0009_auto_20201228_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, unique=True)),
                ('descripcion', models.CharField(help_text='En que consiste el servicio', max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='medicos',
            name='servicio',
            field=models.CharField(help_text='Especialidad', max_length=50, null=True),
        ),
    ]
