# Generated by Django 3.1.4 on 2020-12-29 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0010_auto_20201229_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Medicos.servicios'),
        ),
    ]
