# Generated by Django 3.1.4 on 2020-12-29 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Medicos', '0011_auto_20201229_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='entrada',
            field=models.CharField(help_text='Hora de entrada', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='medico',
            field=models.ForeignKey(help_text='Usuario asignado a medico', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='nombre',
            field=models.CharField(help_text='Nombre completo de usuario', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='salida',
            field=models.CharField(help_text='Hora de salida', max_length=50, null=True),
        ),
    ]
