# Generated by Django 3.1.4 on 2020-12-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo de usuario', max_length=50, null=True)),
                ('apellido_p', models.CharField(help_text='Apellido paterno', max_length=50, null=True)),
                ('apellido_m', models.CharField(help_text='Apellido materno', max_length=50, null=True)),
                ('edad', models.IntegerField(null=True)),
                ('contacto', models.CharField(help_text='Manera por la cual nos podemos poner en contacto con paciente ya sea correo, celular o telefono de casa', max_length=50, null=True)),
            ],
        ),
    ]
