# Generated by Django 3.1.4 on 2020-12-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='hora_atendido',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
