# Generated by Django 3.1.4 on 2020-12-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20201230_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='contacto',
            field=models.CharField(help_text='Manera por la cual nos podemos poner en contacto con paciente ya sea correo, celular o telefono de casa (esta seccion puede quedar vacia)', max_length=255, null=True),
        ),
    ]
