# Generated by Django 3.1.4 on 2020-12-31 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Medicos', '0012_auto_20201229_2135'),
        ('pacientes', '0005_pacientes_atendiendo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='nombre',
            field=models.CharField(help_text='Nombre completo del paciente', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nombre_paciente', models.CharField(help_text='Nombre completo del paciente', max_length=50, null=True)),
                ('dia_hora_cita', models.DateTimeField(help_text='Dia y hora de cita.Ejemplo: 10/25/06 14:30', max_length=50, null=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Medicos.servicios')),
            ],
        ),
    ]
