# Generated by Django 3.1.4 on 2020-12-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_auto_20201231_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='dia_hora_cita',
            field=models.DateTimeField(help_text='Dia y hora de cita.Formato AAAA-MM-DD H-M-S Ejemplo: 2021-01-17 14:30', max_length=50, null=True),
        ),
    ]
