# Generated by Django 3.1.4 on 2020-12-31 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacientes', '0008_auto_20201231_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creada', models.DateTimeField(auto_now_add=True, null=True)),
                ('medicina', models.CharField(help_text='Medicina que se esta recetando', max_length=50, null=True)),
                ('nombre_paciente', models.CharField(help_text='Nombre completo del paciente', max_length=50, null=True)),
                ('fecha_vencimiento', models.DateTimeField(help_text='Hasta que fecha ser tiene para usar.Formato AAAA-MM-DD H-M-S Ejemplo: 2021-01-17 14:30', null=True)),
                ('descripcion', models.CharField(help_text='Detalles como cantidad y cada cuanto tomar', max_length=50, null=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
