# Generated by Django 3.1.4 on 2020-12-31 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_receta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='fecha_vencimiento',
            field=models.DateTimeField(help_text='Hasta que fecha ser tiene para usar.Formato AAAA-MM-DD Ejemplo: 2021-01-17', null=True),
        ),
    ]
