# Generated by Django 3.1.4 on 2021-01-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0011_auto_20201231_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='descripcion',
            field=models.CharField(help_text='Detalles como cantidad y cada cuanto tomar', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='medicina',
            field=models.CharField(help_text='Medicina que se esta recetando', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='nombre_paciente',
            field=models.CharField(help_text='Nombre completo del paciente', max_length=255, null=True),
        ),
    ]
